"""add EA installation registry

Revision ID: 5db4b8c39b75
Revises: ac55fbaef9dd
Create Date: 2026-09-14 21:44:09.929368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5db4b8c39b75"
down_revision: Union[str, Sequence[str], None] = "ac55fbaef9dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ea_installations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ea_id", sa.String(length=100), nullable=False),
        sa.Column("terminal_name", sa.String(length=200), nullable=False),
        sa.Column("terminal_path", sa.Text(), nullable=False),
        sa.Column("experts_directory", sa.Text(), nullable=False),
        sa.Column("executable_name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ea_installations_ea_id"), "ea_installations", ["ea_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ea_installations_ea_id"), table_name="ea_installations")
    op.drop_table("ea_installations")
    # ### end Alembic commands ###
