"""create EA platform core tables

Revision ID: 6be682103b51
Revises:
Create Date: 2026-09-14 03:09:59.547244

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6be682103b51"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ea_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ea_id", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("previous_status", sa.String(length=50), nullable=True),
        sa.Column("current_status", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ea_events_created_at"), "ea_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ea_events_ea_id"), "ea_events", ["ea_id"], unique=False)
    op.create_index(
        op.f("ix_ea_events_event_type"), "ea_events", ["event_type"], unique=False
    )
    op.create_table(
        "ea_instances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ea_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("magic_number", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ea_instances_ea_id"), "ea_instances", ["ea_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ea_instances_ea_id"), table_name="ea_instances")
    op.drop_table("ea_instances")
    op.drop_index(op.f("ix_ea_events_event_type"), table_name="ea_events")
    op.drop_index(op.f("ix_ea_events_ea_id"), table_name="ea_events")
    op.drop_index(op.f("ix_ea_events_created_at"), table_name="ea_events")
    op.drop_table("ea_events")
    # ### end Alembic commands ###
