"""Add EA artifact registry

Revision ID: ac55fbaef9dd
Revises: 9032ef62a183
Create Date: 2026-09-14 16:23:03.805334

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ac55fbaef9dd"
down_revision: Union[str, Sequence[str], None] = "9032ef62a183"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ea_artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ea_id", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ea_id", "version", "sha256", name="uq_ea_artifact_version_hash"
        ),
    )
    op.create_index(
        op.f("ix_ea_artifacts_ea_id"), "ea_artifacts", ["ea_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ea_artifacts_ea_id"), table_name="ea_artifacts")
    op.drop_table("ea_artifacts")
    # ### end Alembic commands ###
